extract odk data
robert-koch-institut/mex-extractors pull request #10
Opened 2024-02-14 10:52 UTC by erichesse

# PR Context

# Added
- add odk extract

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-02-16 13:06 UTC, cutoffthetop requested changes

2024-02-16 13:06 UTC, cutoffthetop commented on tests/odk/test_extract.py
> +    assert test[0].model_dump(exclude_defaults=True) == expected
small unittest for `get_column_dict_by_pattern` would be nice

2024-02-16 13:06 UTC, cutoffthetop commented on mex/odk/model.py
> +    label_survey: dict[str, list[str | float]]
why did you go with go with lists of column values instead of one model per row?

2024-02-16 14:22 UTC, erichesse commented on assets/mappings/__final__/odk/resource_3rdWave-NAM.yaml
> +# yaml-language-server: $schema=../../__schema__/ExtractedResource_MappingSchema.json
I did this to get the test coverage of odk/main to over 95%.

I now redirected the files to test_mapping, so we don't need to maintain mappings for "every" x-system. Also made them a little more generic.

https://github.com/robert-koch-institut/mex-extractors/pull/10/commits/47a599c07a483fa458c22ce5c7c32e4466c42c22

2024-02-16 15:01 UTC, erichesse commented on tests/odk/test_extract.py
> +    assert test[0].model_dump(exclude_defaults=True) == expected
https://github.com/robert-koch-institut/mex-extractors/pull/10/commits/8dc2471d941370d7953638751faeaee8ce525848

2024-02-16 15:04 UTC, erichesse commented on mex/odk/model.py
> +    label_survey: dict[str, list[str | float]]
The basic data structure here are not rows, but rather groups marked by "begin_group" and "end_group" in the "type" column. 

To properly validate that, you would already need to do complex data transformation. But doing that in the extraction step would violate the "separation of concern" principle.

2024-02-19 11:42 UTC, cutoffthetop commented on mex/odk/model.py
> +    label_survey: dict[str, list[str | float]]
uff, i see. but i do agree that this is the way to go then

2024-02-19 11:52 UTC, cutoffthetop commented on assets/mappings/__final__/odk/resource_3rdWave-NAM.yaml
> +# yaml-language-server: $schema=../../__schema__/ExtractedResource_MappingSchema.json
alright, let's see how this works out. do you think we could do the same for the other mapping yamls? shouldn't be on this branch, just curious about your assessment and whether we should create a follow-up task.

one config-issue though; i would prefer setting the default in `ODKSettings` to the generic mappings and then pointing the setting in dev/stage/prod to the actual path. that way, the extractor would remain runnable in its default configuration even when the assets repository is not set up.

2024-02-19 14:54 UTC, erichesse commented on assets/mappings/__final__/odk/resource_3rdWave-NAM.yaml
> +# yaml-language-server: $schema=../../__schema__/ExtractedResource_MappingSchema.json
yes, this is a good idea. I created a ticket for that: MX-1570

I liked to also manually run e.g. `poetry run odk` with the actually mappings to see whether it works on top of tests. Althoug I can see how that is not best practices. Another issue is, that with that change the default value extraction will not be visible in the locally dumped ndjson but only in staging. Anyway I redirected the settings: https://github.com/robert-koch-institut/mex-extractors/pull/10/commits/3f5f4475fc6804e0a9a6f559009235729a4caf4a

2024-02-21 15:03 UTC, cutoffthetop approved these changes
lgtm ✨ :shipit:

2024-02-21 15:13 UTC, merged