[WIP] Feature/mx 1583 make asset dependencies explicit
robert-koch-institut/mex-extractors pull request #103
Opened 2024-06-18 06:52 UTC by rababerladuseladim

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-06-20 14:55 UTC, cutoffthetop requested changes
very nice tidying up 🧹✨ just tiny remarks.

2024-06-20 14:55 UTC, cutoffthetop commented on mex/confluence_vvt/main.py
> +def extracted_confluence_vvt_activities(
oh, still some model v1 relics..

2024-06-20 14:55 UTC, cutoffthetop commented on mex/confluence_vvt/transform.py
> +def transform_confluence_vvt_sources_to_mex_activities(
```suggestion
def transform_confluence_vvt_sources_to_extracted_activities(
```

maybe even this, while we're at it

2024-06-20 14:55 UTC, cutoffthetop commented on mex/confluence_vvt/transform.py
> +            identifierInPrimarySource=source.identifier_in_primary_source,
looks like the "source" model is already transformed :(

i created MX-1631 to clean that up.

2024-06-20 14:55 UTC, cutoffthetop commented on tests/biospecimen/test_transform.py
> +    synopse_merged_id = [  # noqa: RUF015
i mean, just a test, why not next()?

2024-06-20 14:55 UTC, cutoffthetop commented on tests/confluence_vvt/test_transform.py
> +    mex_activity = mex_activities[0]
next no good?

2024-06-27 07:31 UTC, rababerladuseladim commented on tests/biospecimen/test_transform.py
> +    synopse_merged_id = [  # noqa: RUF015
next does not work on list comprehensions, no idea why ruff suggests it here. Anyway, replaced the list comprehension with `filter` in 9e86f2a4867091c439a0839acc5e39346934f552

2024-06-27 07:31 UTC, rababerladuseladim commented on tests/confluence_vvt/test_transform.py
> +    mex_activity = mex_activities[0]
next does not work on list comprehensions, no idea why ruff suggests it here. Anyway, replaced the list comprehension with `filter` in 9e86f2a4867091c439a0839acc5e39346934f552

2024-06-27 08:31 UTC, rababerladuseladim commented on mex/confluence_vvt/transform.py
> +def transform_confluence_vvt_sources_to_mex_activities(
done in 01db3ac38a89886407e5d6c1f5228dae6d3b8377

2024-07-02 07:19 UTC, cutoffthetop approved these changes

2024-07-02 08:36 UTC, merged