model update ff projects
robert-koch-institut/mex-extractors pull request #164
Opened 2024-08-05 12:08 UTC by erichesse

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-08-13 14:12 UTC, cutoffthetop requested changes
looks good, just one question

.. and i have 2 failing tests, do they work on your machine?

```
FAILED tests/ff_projects/test_main.py::test_job - mex.common.exceptions.MExError: MExError: missing unit should have been filtered out
FAILED tests/ff_projects/test_filter.py::test_filter_and_log_ff_projects_sources - assert 15 == 2
```

2024-08-13 14:12 UTC, cutoffthetop commented on mex/extractors/ff_projects/extract.py
> +}
can't we read this from the mapping?
i know, currently it's not quite machine-friendly, but we could just put the values to use into `setValues`, no?

2024-08-13 15:30 UTC, erichesse commented
> looks good, just one question
> 
> .. and i have 2 failing tests, do they work on your machine?
> 
> ```
> FAILED tests/ff_projects/test_main.py::test_job - mex.common.exceptions.MExError: MExError: missing unit should have been filtered out
> FAILED tests/ff_projects/test_filter.py::test_filter_and_log_ff_projects_sources - assert 15 == 2
> ```

The filtering is a weird issue itself, I don't really find it in the mapping. I think we need to for the metadata check...

2024-08-13 15:33 UTC, erichesse commented on mex/extractors/ff_projects/extract.py
> +}
I made a remark in the ticket, to change the mapping accordingly.

2024-08-14 12:56 UTC, erichesse commented
> > looks good, just one question
> > .. and i have 2 failing tests, do they work on your machine?
> > ```
> > FAILED tests/ff_projects/test_main.py::test_job - mex.common.exceptions.MExError: MExError: missing unit should have been filtered out
> > FAILED tests/ff_projects/test_filter.py::test_filter_and_log_ff_projects_sources - assert 15 == 2
> > ```
> 
> The filtering is a weird issue itself, I don't really find it in the mapping. I think we need to for the metadata check...

I reverted the changes that broke the tests and created MX-1671 for wrap up. I think we should merge model update like this now,

2024-08-16 14:19 UTC, cutoffthetop approved these changes

2024-08-16 14:24 UTC, merged