Feature/mx 1566 transform odk data
robert-koch-institut/mex-extractors pull request #19
Opened 2024-03-05 13:49 UTC by erichesse

# PR Context

# Added
- transform odk data

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-03-11 13:23 UTC, rababerladuseladim submitted a review, later dismissed
Nice work, another complicated extractor down!

My remarks: 
- Text language: we so far only support english and german. Should we filter out all the other values? Or should we add the other languages? Probably a question for Franzi. Also, for german and english labels we could retain the info from the column name and pass it to the Text object instead of accepting mis-detection by the language detector. For the non-english or german labels, we could explicitely set the language to None to avoid mis-detection.
- update README with current mappings commit sha

2024-03-11 13:23 UTC, rababerladuseladim commented on tests/odk/conftest.py
> +                            "forValues": ["invidunt"],
make this multiple values

2024-03-11 13:23 UTC, rababerladuseladim commented on tests/odk/conftest.py
> +                            "forValues": ["consetetur", " sadipscing  "],
add an extractable org at non-first position.

2024-03-11 13:23 UTC, rababerladuseladim commented on tests/odk/conftest.py
> +
These are not used.
```suggestion
```

2024-03-11 13:23 UTC, rababerladuseladim commented on tests/odk/test_transform.py
> +    expected = {
Maybe compare against more than one expected variable? I know it's a lot of work but only then we really know wether the the dynamic transformation works.

2024-03-12 11:58 UTC, rababerladuseladim commented on mex/odk/transform.py
> +                resource["contributingUnit"][0]["mappingRules"][0]["forValues"][0]
This could also be multiple, we need to look up each one.

2024-03-12 13:59 UTC, erichesse commented on mex/odk/transform.py
> +            )
fixed https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/78c3e79d1f17164671d9f667532a982cd6133eee

2024-03-12 13:59 UTC, erichesse commented on mex/odk/transform.py
> +        if (
fixed here as well

2024-03-12 15:16 UTC, erichesse commented on mex/odk/transform.py
> +        was_generated_by = None
Do we? fixed it, but no we can't use `poetry run odk` locally anymore, as it depends on international-projects

https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/17033af1f3ee99172bb58de8dbc73fe9c8c759ed

2024-03-12 15:42 UTC, erichesse commented on mex/odk/transform.py
> +    )
fixed https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/c08c0207ee1635b42aefc29f4d2ccf79d2cd4df4

2024-03-12 15:43 UTC, erichesse commented on mex/odk/transform.py
> +        if organization := list(search_organization_by_label(label)):
Will be adressed by MX-1502

2024-03-12 15:50 UTC, erichesse commented on mex/odk/transform.py
> +        belongs_to = variable_group_identifier_in_primary_source[group_name]
added this as a question to MX-1568

2024-03-12 16:02 UTC, erichesse commented on mex/odk/transform.py
> +                if "label" in column_name and isinstance(cell, str)
fixed https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/268bc745b21407967e2652a5d9e56f24049d8156

2024-03-12 16:04 UTC, erichesse commented on mex/odk/transform.py
> +                continue  # TODO: address empty label list in MX-1568
I added it to Description. As it's not clear yet, what to do about it, it is not ready yet to be formulated as AC

2024-03-12 16:07 UTC, erichesse commented on mex/odk/main.py
> +def extracted_variable_odk(
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/b27e48a47bd6b1154fa78cc65d54b0785af4e832

2024-03-12 16:28 UTC, erichesse commented on tests/odk/test_transform.py
> +        "publisher": [external_partner_and_publisher_by_label["invidunt"]],
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/1603d5d4b925620f54453a7c5dca34ecb29607c7

2024-03-12 16:28 UTC, erichesse commented on tests/odk/conftest.py
> +                            "forValues": ["consetetur", " sadipscing  "],
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/1603d5d4b925620f54453a7c5dca34ecb29607c7

2024-03-12 16:29 UTC, erichesse commented on tests/odk/conftest.py
> +                            "forValues": ["invidunt"],
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/1603d5d4b925620f54453a7c5dca34ecb29607c7

2024-03-12 16:30 UTC, erichesse commented on tests/odk/conftest.py
> +                            "setValues": ["http://id.nlm.nih.gov/mesh/D000086382"],
I generated the object by using the extracting method. So yeah, this is the data how the mapping connector extracts the data.

2024-03-13 08:32 UTC, erichesse commented on tests/odk/conftest.py
> +
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/4403c22bb596dd306b8592cdf74a33eb085bca5e

2024-03-13 08:37 UTC, erichesse commented on tests/odk/test_transform.py
> +    expected = {
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/eae2a4c5621b045e1767d0c9462f0b751a6f4b8e

2024-03-13 08:45 UTC, erichesse commented on mex/odk/transform.py
> +                resource["contributingUnit"][0]["mappingRules"][0]["forValues"][0]
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/f0c74a34f1cb650f027d956c7079a8a5b7faf780

2024-03-13 08:53 UTC, erichesse commented
> * e other values? Or should we add the other languages? Probably a question for Franzi. Also, for german and english labels we co

1. Added the question MX-1468
2. https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/2e24b84fac33f10a3d5f796d34230b735b2309f2

2024-03-19 09:20 UTC, cutoffthetop commented
nice, most of henning's comments are resolved. i also found a few smaller things, but its getting close to the finishline! 🏁

2024-03-19 16:37 UTC, cutoffthetop requested changes

2024-03-21 15:04 UTC, erichesse commented on mex/odk/transform.py
> +            ]
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/b29ce07ec6716936e247d5ecd5ea1ce55f547f36

2024-03-21 15:06 UTC, erichesse commented
I made the international project reference a soft dependency again: https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/f1473aefa517705708a6d2eb6160d233734b606a

I created MX-1583 to discuss how we want to adress these kind of issues in general

2024-03-21 15:09 UTC, erichesse commented on mex/odk/transform.py
> +            if isinstance(type_row, str) and isinstance(name, str):
https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/ad2c5b525d946d4a969294721546cabb1c59e881

2024-03-21 15:17 UTC, erichesse commented on mex/odk/transform.py
> +            name = file.name[i]
That's not overloading, I need the row index for label and hint columns there.

I tried to give it a more meaningful name: https://github.com/robert-koch-institut/mex-extractors/pull/19/commits/585487e29e99a66de20cefae7b08867327904bca

2024-03-22 09:58 UTC, cutoffthetop approved these changes
let's go 🏎️

2024-03-22 10:41 UTC, erichesse commented
I can't merge it

2024-03-22 11:26 UTC, merged