model update grippeweb
robert-koch-institut/mex-extractors pull request #216
Opened 2024-09-18 13:34 UTC by erichesse

# PR Context
- blocked by fixing confluence vvt

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-09-23 14:31 UTC, cutoffthetop requested changes
looks good overall, tests and linters are green!
just a couple of questions

2024-09-23 14:31 UTC, cutoffthetop commented on assets/mappings/__final__/grippeweb/resource_grippeweb-plus.yaml
> +          value: "Alle Personen aus dem Bundesgebiet ab einem Mindestalter von 16 Jahren sind zur Teilnahme berechtigt,
could you use more generic dummy text here and below for the publication field

2024-09-23 14:31 UTC, cutoffthetop commented on assets/mappings/__final__/grippeweb/resource_grippeweb-plus.yaml
> +        rule: Skip extraction. Add the bibliographic resources with the editor.
where is this skipping implemented? i can't find it

2024-09-23 14:31 UTC, cutoffthetop commented on mex/extractors/grippeweb/transform.py
> +            ]
could you explain (in a code comment) why wasGeneratedBy was dropped from the mapping but is still optionally transformed here?

2024-09-23 14:31 UTC, cutoffthetop commented on assets/mappings/__final__/grippeweb/resource_grippeweb.yaml
> +          value: "Alle Personen aus dem Bundesgebiet ab einem Mindestalter von 16 Jahren sind zur Teilnahme berechtigt,
same in this file, please use more obvious dummy values

2024-09-23 14:31 UTC, cutoffthetop commented on tests/grippeweb/mocked_grippeweb.py
> +            "hasLegalBasis": [
why can't we parse `mex-extractors:assets/mappings/__final__/grippeweb/resource_grippeweb.yaml` and use that for the mock?

2024-09-23 14:31 UTC, cutoffthetop commented on CHANGELOG.md
> +- model update: international-projects, seqrepo, synopse, blueant, sumo, biospecimen, grippeweb
this needs a merge

2024-09-24 13:01 UTC, erichesse commented on CHANGELOG.md
> +- model update: international-projects, seqrepo, synopse, blueant, sumo, biospecimen, grippeweb
merged model-update-v3 branch into this one!

2024-09-24 13:05 UTC, erichesse commented on tests/grippeweb/mocked_grippeweb.py
> +            "hasLegalBasis": [
I thought that is bad practice. As I understand it, tests should be as much isolated as possible and not be interdependent with other parts of the code base.

2024-09-24 13:24 UTC, erichesse commented on assets/mappings/__final__/grippeweb/resource_grippeweb-plus.yaml
> +        rule: Skip extraction. Add the bibliographic resources with the editor.
I interpreted as a passive `ignore` and hence didn't implement anything. However I wrote a comment to the wrap up ticket [MX-1716] and asked for clarification.

2024-09-24 13:24 UTC, erichesse commented on assets/mappings/__final__/grippeweb/resource_grippeweb.yaml
> +          value: "Alle Personen aus dem Bundesgebiet ab einem Mindestalter von 16 Jahren sind zur Teilnahme berechtigt,
https://github.com/robert-koch-institut/mex-extractors/pull/216/commits/5ab2766b2130da345540180e5d0456c2cc3b7565

2024-09-24 13:25 UTC, erichesse commented on mex/extractors/grippeweb/transform.py
> +            ]
https://github.com/robert-koch-institut/mex-extractors/pull/216/commits/5ab2766b2130da345540180e5d0456c2cc3b7565

2024-09-24 13:25 UTC, erichesse commented on assets/mappings/__final__/grippeweb/resource_grippeweb-plus.yaml
> +          value: "Alle Personen aus dem Bundesgebiet ab einem Mindestalter von 16 Jahren sind zur Teilnahme berechtigt,
https://github.com/robert-koch-institut/mex-extractors/pull/216/commits/5ab2766b2130da345540180e5d0456c2cc3b7565

2024-09-24 13:25 UTC, erichesse commented on assets/mappings/__final__/grippeweb/resource_grippeweb-plus.yaml
> +        rule: Skip extraction. Add the bibliographic resources with the editor.
I interpreted as a passive `ignore` and hence didn't implement anything. However I wrote a comment to the wrap up ticket [MX-1716] and asked for clarification.

2024-09-24 14:32 UTC, cutoffthetop commented on tests/grippeweb/mocked_grippeweb.py
> +            "hasLegalBasis": [
in general yes, but mostly to keep them easily readable and "portable". which i'd argue is not really the case for this 1481 line file 😅

2024-09-24 14:33 UTC, cutoffthetop approved these changes

2024-09-24 14:33 UTC, cutoffthetop commented on tests/grippeweb/mocked_grippeweb.py
> +            "hasLegalBasis": [
(but since this was not introduced in this PR, we can stick to it for now)

2024-09-24 14:34 UTC, cutoffthetop commented
all good 🎇 ready to merge

2024-09-24 14:35 UTC, merged