include BibliographicResource and fix fake data generation
robert-koch-institut/mex-extractors pull request #221
Opened 2024-09-27 13:28 UTC by esinsj

# Fixed
fixed artificial data generation for Integers and BibliographicResources

2024-10-07 13:15 UTC, rababerladuseladim requested changes
Nice and clean!

Mostly questions and minor remarks.

- [ ] Please also merge main

2024-10-08 07:47 UTC, esinsj commented on mex/extractors/artificial/provider.py
> +        "^(((http)|(https))://(dx.)?doi.org/)(10.\\d{4,9}/[-._;()/:A-Z0-9]+)$": "https://dx.doi.org/10.####/#######",
If I use this string as raw string as a dictionary key, python will smartly interpret the '\\d' part into '\\\\d', and then looked up regex in line 235 isn't matching anymore --> KeyError

2024-10-08 07:53 UTC, esinsj commented on tests/artificial/test_identity.py
> +        "AccessPlatform": range(3427526317, 3427526324),
The way I understand the Faker package and how we use it is that we provide Seeds to give a fixed entry point into 'randomly' created fake data. Each created data point kind of shifts the used 'random' point one further. Because I added new created data for the Resources, the following fake data points were at a different order rank and therefore a different fake data point was created. I had to update a lot because of that.

2024-10-08 08:41 UTC, esinsj commented on tests/artificial/test_provider.py
> +        "has_max": (5, 7),
Here I don't understand your question. Could you please specify?
Do you mean 'min_length' in line 29?

2024-10-08 09:58 UTC, esinsj commented on tests/artificial/test_provider.py
> +        "has_max": (5, 7),
solved together in a session :)

2024-10-08 11:56 UTC, esinsj commented on CHANGELOG.md
done

2024-10-08 12:52 UTC, rababerladuseladim approved these changes

2024-10-09 08:40 UTC, merged