Feature/mx 1581 refine publisher
robert-koch-institut/mex-extractors pull request #262
Opened 2024-10-29 18:26 UTC by esinsj

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-11-01 08:44 UTC, cutoffthetop requested changes
nice and clean overall! just a few simplications/suggestions from my side

2024-11-01 08:44 UTC, cutoffthetop commented on mex/extractors/publisher/extract.py
> +    for item_counter in range(0, total_item_number + 1, item_number_limit):
do we need this `+ 1`? e.g. when i have exactly 800 items, i could get those in 8 requests, not 9 - right?

```python
>>> total_item_number = 800
>>> item_number_limit = 100
>>> list(range(0, total_item_number + 1, item_number_limit))
[0, 100, 200, 300, 400, 500, 600, 700, 800]
```

2024-11-01 08:44 UTC, cutoffthetop commented on mex/extractors/logging.py
> +        logger.info(
i'd move these logger.info statements right into the code, this function doesn't help much with readability imho

2024-11-01 08:44 UTC, cutoffthetop commented on mex/extractors/publisher/filter.py
> +    total_counter = 0
```suggestion
    skipped_items = 0
    total_items = 0
```
maybe that'd be a bit clearer?

2024-11-01 08:44 UTC, cutoffthetop commented on mex/extractors/publisher/main.py
> +    write_merged_items(allowed_items)
what do you think of splitting the get+filter and write into 2 separate assets?

2024-11-05 11:09 UTC, esinsj commented on mex/extractors/publisher/extract.py
> +    for item_counter in range(0, total_item_number + 1, item_number_limit):
we do not only not need it, it even throws an error. Thanks for pointing that out.

2024-11-05 11:18 UTC, esinsj commented on mex/extractors/logging.py
> +        logger.info(
Do you mean to ditch the log_processed_merged_items function and write the logging directly into the extract, filter, and the write functions?

2024-11-05 11:21 UTC, esinsj commented on mex/extractors/publisher/main.py
> +    write_merged_items(allowed_items)
I could do that. Can you explain what the purpose is? Is it simply best practice, even though the write asset would just call the rite_merged_items function?

2024-11-05 13:27 UTC, esinsj commented on mex/extractors/publisher/main.py
> +    write_merged_items(allowed_items)
ah 💡 thanks!

2024-11-06 08:18 UTC, cutoffthetop commented on mex/extractors/logging.py
> +        logger.info(
that was my suggestion yeah. but this is rather a matter of taste, if you think it makes the logging easier to read, go ahead and keep it

2024-11-06 08:19 UTC, cutoffthetop commented on mex/extractors/logging.py
> +        logger.info(
ah, too late ([9ac94b5](https://github.com/robert-koch-institut/mex-extractors/pull/262/commits/9ac94b5e8f3a4c0444e8222af89f19d9d26aca25)), just as well

2024-11-06 08:19 UTC, cutoffthetop approved these changes
looks good! let's ship 🚢

2024-11-06 08:20 UTC, merged