wrap up blueant
robert-koch-institut/mex-extractors pull request #270
Opened 2024-11-05 08:54 UTC by erichesse

# PR Context
regex: https://regex101.com/r/EVN4ad/1
-wrap up blueant
-based on mex-assets branch `feature/mx-1686-wrap-up-blueant`

2024-11-06 14:16 UTC, cutoffthetop requested changes
looks good, just some questions on the title

2024-11-06 14:16 UTC, cutoffthetop commented on mex/extractors/blueant/transform.py
> +            title = source_name
```suggestion
            title = source_name
        else:
            title = []
```

2024-11-06 14:16 UTC, cutoffthetop commented on mex/extractors/blueant/transform.py
> +            r"[\d*_]+|[FG\d* ]+[- ]+", "", source.name
ZV prefix is ok though? or will it be skipped anyway

2024-11-06 15:30 UTC, erichesse commented on mex/extractors/blueant/transform.py
> +            r"[\d*_]+|[FG\d* ]+[- ]+", "", source.name
the rule is `Delete underscore (_) and number_ if used as prefix in a label`, so I think we can keep `ZV` here. Plus I got the check mark in the ticket table for the title field. So I think I'm covered here.

2024-11-07 14:00 UTC, erichesse commented
your suggestion I signed of in transform.py:89 is causing a mypy error @cutoffthetop 
You sure, this is needed here? The None case is covered below anyway

2024-11-07 15:06 UTC, cutoffthetop approved these changes

2024-11-07 15:06 UTC, merged