feature/mx-1664-use-wikidata-helper
robert-koch-institut/mex-extractors pull request #279
Opened 2024-11-08 16:05 UTC by esinsj

# PR Context

# Added

# Changes

# Fixed
- typo sySnopse

2024-11-14 16:16 UTC, esinsj commented on tests/ff_projects/test_extract.py
> +    )
I'm not happy about this solution, but I couldn't find where "wikidata_organization" is defined (in the "mocked_wikidata"?)
Any suggestions?

2024-11-15 13:56 UTC, esinsj commented on mex/extractors/biospecimen/transform.py
>          activity.identifierInPrimarySource: activity.stableTargetId
Just a correction of a type (sy*_s_*nopse)

2024-11-19 09:56 UTC, esinsj commented on mex/extractors/international_projects/extract.py
> -        organizations_str.replace(",,", ",").replace("»", "").replace("•", "")
small improvement: add more special characters which can be irgnored. 
(fun fact: "..." find's the rock band "...And You Will Know Us by the Trail of Dead" on wikidata: https://www.wikidata.org/entity/Q426068)

2024-11-25 14:24 UTC, esinsj commented on tests/grippeweb/test_extract.py
>      }
Same as above. Can we use the mocked_wikidata?

2024-11-25 14:24 UTC, esinsj commented on tests/voxco/test_extract.py
>      }
Same as above. Can we use the mocked_wikidata?

2024-12-09 11:20 UTC, cutoffthetop requested changes
looks good! i have just a formality: could you update the CHANGELOG and pr-description please?

and one other thing i noticed while reviewing:
these wikidata fixtures here https://github.com/robert-koch-institut/mex-extractors/blob/feature/mx-1664-use-wikidata-helper/tests/conftest.py#L44-L119 seem to be an exact copy of https://github.com/robert-koch-institut/mex-common/blob/0.42.0/mex/common/testing/plugin.py#L125-L193
could you trash those fixtures in mex-extractors (along with the [test_data](https://github.com/robert-koch-institut/mex-extractors/tree/feature/mx-1664-use-wikidata-helper/tests/test_data) folder) and check if the tests still work? in theory they _should_, since the mex-common fixtures are loaded as a plugin anyway.

2024-12-09 11:20 UTC, cutoffthetop commented on tests/ff_projects/test_extract.py
> +    )
the ID is built here, deterministic and collision-proof https://github.com/robert-koch-institut/mex-common/blob/0.42.0/mex/common/identity/memory.py#L31-L40
should be fine to hardcode it

2024-12-10 10:57 UTC, esinsj commented
> looks good! i have just a formality: could you update the CHANGELOG and pr-description please?
> 
> and one other thing i noticed while reviewing: these wikidata fixtures here https://github.com/robert-koch-institut/mex-extractors/blob/feature/mx-1664-use-wikidata-helper/tests/conftest.py#L44-L119 seem to be an exact copy of https://github.com/robert-koch-institut/mex-common/blob/0.42.0/mex/common/testing/plugin.py#L125-L193 could you trash those fixtures in mex-extractors (along with the [test_data](https://github.com/robert-koch-institut/mex-extractors/tree/feature/mx-1664-use-wikidata-helper/tests/test_data) folder) and check if the tests still work? in theory they _should_, since the mex-common fixtures are loaded as a plugin anyway.

I left in the extracted_organization_rki, because that wasn't specified in the mex-common fixtures, but is used by the extractor test.

2024-12-10 13:21 UTC, cutoffthetop approved these changes

2024-12-10 14:26 UTC, merged