feature/mx-1714 wrap up odk
robert-koch-institut/mex-extractors pull request #294
Opened 2024-11-29 17:12 UTC by erichesse

# Changes
- wrap up odk model v3 update

2025-01-10 13:14 UTC, cutoffthetop requested changes
looks good so far! 👍 just 2 minor comments

2025-01-10 13:14 UTC, cutoffthetop commented on mex/extractors/odk/transform.py
> +                                                     projects activitiess
```suggestion
                                                     projects activities
```

2025-01-10 13:14 UTC, cutoffthetop commented on mex/extractors/odk/transform.py
> +                    value_set_choices.append(name)
this case doesn't seem to be present in the test data / cases

2025-01-14 09:21 UTC, erichesse commented on mex/extractors/odk/transform.py
> +                    value_set_choices.append(name)
covered this case in the test data: https://github.com/robert-koch-institut/mex-extractors/pull/294/commits/25d921fda736381908e2cad067f30cb4d5990bef

2025-01-14 09:23 UTC, cutoffthetop approved these changes

2025-01-14 13:45 UTC, merged