[WIP] Feature/mx 1502 wikidata results refactor
robert-koch-institut/mex-extractors pull request #39
Opened 2024-03-25 13:29 UTC by mr-kamran-ali

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-04-05 10:03 UTC, mr-kamran-ali commented on tests/international_projects/test_transform.py
> +    end.precision = TemporalEntityPrecision.DAY
this switched the object from `TemporalEntity` to `YearMonthDay`, hence failing the test because these two objects are not the same. What do you suggest?

2024-04-09 15:13 UTC, erichesse reviewed
I investigated the ODK `load` issue, unfortunately I'm more confused than before. Anyway I summed up my thoughts on it.

2024-04-09 15:13 UTC, erichesse commented on mex/odk/transform.py
> +        identities = identity_provider.fetch(
I try to pinpoint why it's not working and it's weird. In my opinion the following should work:
```
external_partner_and_publisher_by_label: dict[str, MergedOrganizationIdentifier] = (
        {}
    )
    for label in labels:
        if organization := search_organization_by_label(label):
            extracted_organization = (
                transform_wikidata_organizations_to_extracted_organizations(
                    [organization], extracted_primary_source_wikidata
                )
            )
            load(extracted_organization)
            external_partner_and_publisher_by_label[label] = (
                MergedOrganizationIdentifier(
                    next(extracted_organization).stableTargetId
                )
            )

    return external_partner_and_publisher_by_label
```
But when running the test the `next` throws `RuntimeError: generator raised StopIteration`, I didn't managed to figure out what's going on here. 

That being said I'm also not so convinced by the merged wikidata update in `mex-common`. Now the public `extract` function returns a single `WikidataOrganization` while the correspong public `transform` function expects an Iterable and returns a Generator. I find that super confusing in terms of architecture.

A valid question Kamran raises, is whether we should always `load` in `main`. I didn't do that, since in this usecase I wasn't really interested in assets with the `ExtractedOrganization` but only in the `stableTargetId`, so I decided to return a `dict` of the latter instead.

2024-04-10 07:38 UTC, mr-kamran-ali commented on mex/odk/transform.py
> +        identities = identity_provider.fetch(
Hi Eric, thanks for checking odk out. 

Generator StopIteration on `next` could be because its exhausted already? can you tell me which test you were working on?

Regarding single `WikidataOrganization` result from `wikidata search` and `wikidata transform` expecting an iterable is because in most extractors we have multiple organizations to check in wikidata e.g. in all the sources; this is done in loop and if `search wikidata` returns an org we put that into a dict. And `transform wikidata` simply expects the `WikidataOrganization` values from that dict, which is an iterable. 

I thought about it and `wikidata transform` returning one org didnt make much sense to me, this way we'd have to loop in some dagster asset while collecting single `transformed wikidata orgs` and generating a dict or list anyway. Too much extra lines of code for no apparent benefit. 

Regatding `wikidata transform` Generator: we can get rid of `wikidata transform` generator and directly compile a list and return a list instead of generators, this maybe will slowdown the process a little bit and consume more memory. But this wont be a huge impact and still can be done if `Generators` really annoy you 😄

2024-04-10 07:40 UTC, mr-kamran-ali commented
> I investigated the ODK `load` issue, unfortunately I'm more confused than before. Anyway I summed up my thoughts on it.

If I have your ok, I can take care of this as well by making the process very similar to other extractors wikidata implementation. that is to separate extraction, transformation and load in main file.

2024-04-10 11:08 UTC, cutoffthetop requested changes

2024-04-10 11:08 UTC, cutoffthetop commented on mex/odk/transform.py
> +        identities = identity_provider.fetch(
- regarding Generators, yes we want to stop using those where they don't make sense
  - so everywhere where we are going to do `list(foo())` later anyway, `foo` should directly return a list
- regarding `transform_wikidata_organizations_to_extracted_organizations` we could split that up and provide a `transform_wikidata_organization_to_extracted_organization` alongside it
- regarding the `load` in the `transform`, we should definitely move that into the `main` (i'm sorry i didn't spot that in https://github.com/robert-koch-institut/mex-extractors/pull/19 already)
- and lastly, there is a bunch of code duplication surrounding `get_organization_merged_id_by_query` (in sumo, ff-projects and int-projects) - do you think we can reduce that?

2024-04-16 14:06 UTC, mr-kamran-ali reviewed
@cutoffthetop Temporal entity stuff in `international projects extract and its testing`, is still not perfect yet, have a look at changes in mex-common(https://github.com/robert-koch-institut/mex-common/pull/157), they need to be merged as well, its a breaking change if this PR is merged into mex-extractors main.

2024-05-16 12:54 UTC, cutoffthetop approved these changes

2024-05-16 12:57 UTC, merged