Feature/mx1589 dagster job for running all extractors
robert-koch-institut/mex-extractors pull request #69
Opened 2024-05-21 09:51 UTC by rababerladuseladim

# PR Context

# Added

- entrypoint `all-extractors`: run all extractors

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-05-23 13:23 UTC, cutoffthetop requested changes
very nice! i like the cleanup of the ldap mocks 🫶 

just a few cosmetic change requests

2024-05-23 13:23 UTC, cutoffthetop commented on tests/confluence_vvt/mocked_confluence_vvt.py
> +from _pytest.monkeypatch import MonkeyPatch
```suggestion
from pytest import MonkeyPatch
```

2024-05-23 13:23 UTC, cutoffthetop commented on tests/datscha_web/mocked_datscha_web.py
> +from _pytest.monkeypatch import MonkeyPatch
```suggestion
from pytest import MonkeyPatch
```

2024-05-23 13:23 UTC, cutoffthetop commented on tests/grippeweb/mocked_grippeweb.py
> +def mocked_grippeweb(mocked_grippeweb_sql_tables, monkeypatch: MonkeyPatch) -> None:
```suggestion
def mocked_grippeweb(
    mocked_grippeweb_sql_tables: dict[str, dict[str, Any]], monkeypatch: MonkeyPatch
) -> None:
```

2024-05-23 13:23 UTC, cutoffthetop commented on tests/ifsg/mocked_ifsg.py
> +def mocked_ifsg_sql_tables() -> dict[ModelT, list[BaseModel]]:
```suggestion
@pytest.fixture
def mocked_ifsg_sql_tables() -> dict[type[BaseModel], list[dict[str, Any]]:
```

2024-05-23 13:23 UTC, cutoffthetop commented on tests/ifsg/mocked_ifsg.py
> +def mocked_ifsg(mocked_ifsg_sql_tables, monkeypatch: MonkeyPatch) -> None:
```suggestion
def mocked_ifsg(
    mocked_ifsg_sql_tables: dict[type[BaseModel], list[dict[str, Any]]],
    monkeypatch: MonkeyPatch,
) -> None:
```

2024-05-23 13:23 UTC, cutoffthetop commented on tests/grippeweb/mocked_grippeweb.py
> +def mocked_grippeweb_sql_tables() -> dict[str, list[BaseModel]]:
```suggestion
def mocked_grippeweb_sql_tables() -> dict[str, dict[str, Any]]:
```

2024-05-23 13:23 UTC, cutoffthetop commented on tests/rdmo/mocked_rdmo.py
> +from _pytest.monkeypatch import MonkeyPatch
```suggestion
from pytest import MonkeyPatch
```

2024-05-23 13:23 UTC, cutoffthetop commented on tests/seq_repo/mocked_drop_for_seqrepo.py
> +from _pytest.monkeypatch import MonkeyPatch
```suggestion
from pytest import MonkeyPatch
```

2024-05-24 06:42 UTC, rababerladuseladim commented on tests/blueant/mocked_blueant.py
> +from _pytest.monkeypatch import MonkeyPatch
fixed in cc29b5570bc096bc070e965dbf236534bbf3068f

2024-05-24 06:42 UTC, rababerladuseladim commented on tests/datscha_web/mocked_datscha_web.py
> +from _pytest.monkeypatch import MonkeyPatch
fixed in cc29b5570bc096bc070e965dbf236534bbf3068f

2024-05-24 06:43 UTC, rababerladuseladim commented on tests/rdmo/mocked_rdmo.py
> +from _pytest.monkeypatch import MonkeyPatch
fixed in cc29b5570bc096bc070e965dbf236534bbf3068f

2024-05-24 06:43 UTC, rababerladuseladim commented on tests/seq_repo/mocked_drop_for_seqrepo.py
> +from _pytest.monkeypatch import MonkeyPatch
fixed in cc29b5570bc096bc070e965dbf236534bbf3068f

2024-05-24 06:47 UTC, rababerladuseladim commented on tests/grippeweb/mocked_grippeweb.py
> +def mocked_grippeweb(mocked_grippeweb_sql_tables, monkeypatch: MonkeyPatch) -> None:
fixed in 79b3b8ae6153e3dde8c577f89abf28530006ffab

2024-05-24 06:50 UTC, rababerladuseladim commented on tests/ifsg/mocked_ifsg.py
> +def mocked_ifsg_sql_tables() -> dict[ModelT, list[BaseModel]]:
fixed in f5ffc2323eacf4040ee08fb2820db5f63bd10c3f

2024-05-24 06:50 UTC, rababerladuseladim commented on tests/ifsg/mocked_ifsg.py
> +def mocked_ifsg(mocked_ifsg_sql_tables, monkeypatch: MonkeyPatch) -> None:
fixed in f5ffc2323eacf4040ee08fb2820db5f63bd10c3f

2024-05-24 06:51 UTC, rababerladuseladim commented on tests/grippeweb/mocked_grippeweb.py
> +def mocked_grippeweb_sql_tables() -> dict[str, list[BaseModel]]:
fixed in 79b3b8ae6153e3dde8c577f89abf28530006ffab

2024-05-24 06:55 UTC, rababerladuseladim commented on pyproject.toml
> +all-extractors = "mex.main:run"
I settled for `all-extractors` in 71b895cdcb5f7b680ede99e775f4c49567df982b

2024-05-24 06:57 UTC, rababerladuseladim commented on mex/pipeline/base.py
> +            AssetSelection.groups(*[group for group in group_names]).upstream(),
🙈  7ab1ec8b89c54223b64e9156193b7a5c3178c3b4

2024-05-27 12:53 UTC, cutoffthetop approved these changes
~just needs a main update, then~ good to merge :)

2024-05-27 13:14 UTC, merged