[WIP]integrate mapping extractor into ifsg
robert-koch-institut/mex-extractors pull request #9
Opened 2024-02-08 14:14 UTC by erichesse

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-02-09 11:07 UTC, cutoffthetop requested changes
phew, quite the spring cleaning 🧹✨

could you check for these weird `"foo" "bar"` changes and find out what happened there?

and, could you go over the docstrings of the functions you changed. i pointed out some issues already, but i suspect the type changes created a few more inconsistencies.

2024-02-09 13:14 UTC, erichesse commented on tests/ifsg/conftest.py
> +                                "title": "Infektionsepidemiologisches " "Jahrbuch",
So in the other extractors I did the conversion to dict with multicursor.

But in the ifsg case, I used the old extract and test_extract functions, set a breakpoint, printed the output of the dumped models in the shell and copied the result. I think this might have introduced the artefacts.

They are gone now: https://github.com/robert-koch-institut/mex-extractors/pull/9/commits/34455a6ae72e77aa0fa652b2b1767802356188fa

2024-02-09 13:20 UTC, erichesse commented on mex/ifsg/main.py
> +        AssetsPath(settings.mapping_path / "resource_disease.yaml"), ExtractedResource
in that case mypy will complain:
`mex\sumo\main.py:140: error: Argument 1 to "extract_mapping_model" has incompatible type "Path"; expected "AssetsPath"`
Thas why I forced `AssetsPath` in the first place.

2024-02-09 13:55 UTC, cutoffthetop commented on mex/ifsg/main.py
> +        AssetsPath(settings.mapping_path / "resource_disease.yaml"), ExtractedResource
you'd have to change it to `Path` here as well https://github.com/robert-koch-institut/mex-extractors/blob/main/mex/mapping/extract.py#L8

2024-02-09 14:21 UTC, erichesse commented on mex/ifsg/main.py
> +        AssetsPath(settings.mapping_path / "resource_disease.yaml"), ExtractedResource
https://github.com/robert-koch-institut/mex-extractors/pull/9/commits/cc3a98799a57d6a73e8147773b43edc65fbbfecc

2024-02-09 14:21 UTC, erichesse commented on mex/sumo/main.py
> +    ).model_dump()
https://github.com/robert-koch-institut/mex-extractors/pull/9/commits/14fda808d949bd6fe8f460166cb2ac24746a4d64

2024-02-09 14:35 UTC, erichesse commented on mex/sumo/main.py
> +    ).model_dump()
https://github.com/robert-koch-institut/mex-extractors/pull/9/commits/681f39f5e6a1771131581f10e602628531cc9b25

2024-02-09 14:43 UTC, erichesse commented on mex/seq_repo/models/__init__.py
> +__all__ = ("SeqRepoSource",)
https://github.com/robert-koch-institut/mex-extractors/pull/9/commits/b37722853f81b6af618181211cc85832c7ea2f2f

2024-02-09 15:06 UTC, erichesse commented on mex/ifsg/main.py
>      """Extract `IFSGVariableGroup` default values."""
This is the default value dict based on ifsg/variable-group.yaml. I still think this is the best unique name for this asset

2024-02-09 15:08 UTC, erichesse reviewed
Applied the changes and fixed the doc strings

2024-02-13 09:06 UTC, cutoffthetop commented on tests/ifsg/conftest.py
> +                                "title": "Infektionsepidemiologisches " "Jahrbuch",
ah, did you do `pprint` perhaps? that might have introduced the string splitting

2024-02-13 09:20 UTC, cutoffthetop commented on mex/ifsg/main.py
>      """Extract `IFSGVariableGroup` default values."""
yeah the name is fine, i was just thinking that `'IFSGVariableGroup'` reads misleadingly like a class name

2024-02-13 09:22 UTC, cutoffthetop approved these changes

2024-02-13 09:34 UTC, merged